# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenPrettier < Formula
  desc ""
  homepage "https://github.com/liv7c/gen_prettier"
  version "0.1"

  on_macos do
    url "https://github.com/liv7c/gen_prettier/releases/download/v0.1/gen_prettier_Darwin_all.tar.gz"
    sha256 "5b0af8ad9009a6883dc3bfff0595d35f0bb376ecb451f148263a42149793a80d"

    def install
      bin.install "gen_prettier"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/liv7c/gen_prettier/releases/download/v0.1/gen_prettier_Linux_x86_64.tar.gz"
      sha256 "082cc3114bac6d8f3ef11622e0afb9cb4dae7c977a5fe3c9a9b36f1ee4ae75f2"

      def install
        bin.install "gen_prettier"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liv7c/gen_prettier/releases/download/v0.1/gen_prettier_Linux_arm64.tar.gz"
      sha256 "b03453170b580462245f283db27932e00873445c4ff3bb39fc2bbf95325c300a"

      def install
        bin.install "gen_prettier"
      end
    end
  end
end
