# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenPrettier < Formula
  desc ""
  homepage "https://github.com/liv7c/gen_prettier"
  version "0.4"

  on_macos do
    url "https://github.com/liv7c/gen_prettier/releases/download/v0.4/gen_prettier_Darwin_all.tar.gz"
    sha256 "b8c329d114422ec30f78c7c7ee615413898df62791a77e24ae8d95499c584f4c"

    def install
      bin.install "gen_prettier"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/liv7c/gen_prettier/releases/download/v0.4/gen_prettier_Linux_arm64.tar.gz"
      sha256 "721ce5e0a7a0d06925ad5b5623f853e9c432145bddfba8d72a418db1d3a0e4b4"

      def install
        bin.install "gen_prettier"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/liv7c/gen_prettier/releases/download/v0.4/gen_prettier_Linux_x86_64.tar.gz"
      sha256 "215b821d34fedd56e217ff25ce962984d4b13a3c2bc74673c8483b591c59cc5e"

      def install
        bin.install "gen_prettier"
      end
    end
  end
end
